const ThrowError = () => {
  throw new Error('Oups !');
};

export default ThrowError;
